#ifndef __INC_APPVERSION_H
#define __INC_APPVERSION_H

// EXTERNAL: These are modified by an external script
#define VERSION_NUMBER "7.3.3"
#define VERSION_DATE "20260329"
#define VERSION_TIME "000000"
// END_EXTERNAL

#if (PLATFORM == PLATFORM_WIN64) 
	#define PLATFORM_NAME "Win64"
	#if defined(BETA) && BETA
	#define VERSION_STRING VERSION_NUMBER " Win64 BETA " VERSION_DATE VERSION_TIME
	#elif defined(_DEBUG)
	#define VERSION_STRING VERSION_NUMBER " Win64 DEBUG " VERSION_DATE VERSION_TIME
	#else
	#define VERSION_STRING VERSION_NUMBER " Win64"
	#endif
#endif

#if (PLATFORM == PLATFORM_WIN32)
	#define PLATFORM_NAME "Win32"
	#if defined(BETA) && BETA
	#define VERSION_STRING VERSION_NUMBER " Win32 BETA " VERSION_DATE VERSION_TIME
	#elif defined(_DEBUG)
	#define VERSION_STRING VERSION_NUMBER " Win32 DEBUG " VERSION_DATE VERSION_TIME
	#else
	#define VERSION_STRING VERSION_NUMBER " Win32"
	#endif
#endif

#if (PLATFORM == PLATFORM_MACOSX)
	#define PLATFORM_NAME "macOS"
	#if defined(_DEBUG)
	#define VERSION_STRING VERSION_NUMBER " macOS DEBUG " VERSION_DATE VERSION_TIME
	#else
	#define VERSION_STRING VERSION_NUMBER " macOS"
	#endif
#endif

#if (PLATFORM == PLATFORM_LINUX)
	#define PLATFORM_NAME "Linux"
	#if defined(_DEBUG)
	#define VERSION_STRING VERSION_NUMBER " Linux DEBUG " VERSION_DATE VERSION_TIME
	#else
	#define VERSION_STRING VERSION_NUMBER " Linux"
	#endif
#endif

#endif
